In [5]:
import numpy as np
import pandas as pd

pd.options.plotting.backend = "plotly"
from scipy.stats import binom

In [306]:
t = np.arange(6).reshape(2,3)
indices = np.random.randint(0, 2, 3)
t

array([[0, 1, 2],
       [3, 4, 5]])

In [307]:
indices

array([1, 1, 0])

In [308]:
t[indices, np.arange(3)]

array([3, 4, 2])

In [92]:
# ideas:
# give prior on p
# use MCMC to sample from posterior of hidden variable
# expand to arbitrary number of classes
# solve mixed gaussian in 1d
# solve mixed gaussian in 2d
# infer probabilities of markov model
# how is EM connected to inferring missing probs
# in graphical model? I guess HMM training should be special case of this?

In [315]:
np.random.choice(2, 300) > 1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [322]:
true_classes = np.array([.3, 1 - .3])
true_p = np.array([.1, .75])
m = 10
n = 1000
h = np.random.binomial(np.tile(m, 2), true_p, (n, 2))
# then we select one of the two rows based on
# a weighted coin toss
d = h[np.arange(n), np.random.choice(2, size=n, p=true_classes)]

In [ ]:
# should be an easier way to generate samples?
print(f'true p: {true_p} \ntheta: {true_classes}')
# initial guesses for observable params
cur_p = np.array([.3, .6])
# initial guess for hidden param theta
cur_classes = np.array([.1, 1 - .1])
for i in range(30):
    print(f'p: {cur_p.round(decimals=2)} \ntheta: {cur_classes.round(decimals=2)}')
    # expectation step, compute the weights
    # and from the weights, compute the hidden parameters
    joint = (cur_classes * binom.pmf(np.tile(d, (2, 1)).transpose(), m, cur_p))
    cond_weights = joint.transpose() / joint.sum(axis=1)
    normalized_weights = (cond_weights.transpose() / cond_weights.sum(axis=1)).transpose()
    cur_classes = cond_weights.sum(axis=1)/n
    # now the probabilities
    cur_p = (normalized_weights @ d)/m

In [ ]:
# how does moment generating function allow one to recover PDF?
# sum of binomials are not binomials.
# are normal dist only thing that are also normal under affine
# transformations? what is this property called? This shows up in cosma shalizi notes